[build]
  command = "yarn" # o con yarn: "yarn build".
  functions = "functions" # este comando creará una carpeta llamada "functions" y guardara las funciones Lambda.
  publish = "static" # carpeta que contiene los archivos del proyecto. 

[[redirects]]
  from = "/graphql"
  to = "./.netlify/functions/graphql"
  status = 200
  force = true